package com.mercohuevos.auth.enums;

public enum Rol {
    ADMIN,
    ENCARGADO_GRANJA,
    ENCARGADO_PLANTA_INCUBACION,
    ENCARGADO_VACUNACION,
    LOGISTICA_INCUBACION,
    ENCARGADO_EMBANDEJADO,
    ENCARGADO_NACIMIENTO,
    EMPLEADO,
}